---
prepack:
  exclude: []
  include: []
  include_blank: true

  active_record:
    exclude_database_keys: false
    exclude_timestamps: false
    include_unsaved_changes: false
    include_loaded_associations: false
    max_association_depth: 0
