---
prepack: &prepack
  exclude: []
  include: []
  include_blank: true

  gloabal_id:
    identification:
      <<: *prepack

  active_record:
    base:
      <<: *prepack
      exclude_keys: false
      exclude_timestamps: false
      include_unsaved_changes: false
      include_loaded_associations: false
      max_association_depth: 0
