---
prepack:
  exclude: []
  include: []
  include_blank: true

  database:
    include_keys: true
    include_timestamps: true
    include_changes: false
    include_descendants: false
    descendant_depth: 0
