---
##############################################################################################################
# Prepack options applied before packing with MessagePack
##############################################################################################################
prepack: &prepack
  # ..........................................................................................................
  # A list of attributes to exclude (default includes all keys)
  # Takes prescedence over the`include` list
  exclude: []

  # ..........................................................................................................
  # A list of attributes to include (default includes all keys)
  include: []

  # ..........................................................................................................
  # Whether or not to omit blank values when packing (nil, {}, [])
  include_blank: true

  # ==========================================================================================================
  # ActiveRecord::Base instances/models
  # NOTE: The `prepack` option is ignored
  active_record:
    base:
      <<: *prepack
      # ......................................................................................................
      # Whether or not to omit primary/foreign keys
      # Setting this to `true` can be useful when you want to make a copy of a persisted record
      exclude_keys: false

      # ......................................................................................................
      # Whether or not to omit date/time attributes
      # Setting this to `true` can be useful when you want to make a copy of a persisted record
      exclude_timestamps: false

      # ......................................................................................................
      # Whether or not to preserve unsaved ActiveRecord changes when packing
      # NOTE: New record changes are always preserved regardless of this setting
      include_unsaved_changes: false

      # ......................................................................................................
      # Whether or not to include associations
      # NOTE: Associations must already be loaded (unloaded associations are excluded)
      include_loaded_associations: false

      # ......................................................................................................
      # The max depth (number) of loaded associations to include if `include_loaded_associations == true`
      # Example: a value of (3) would include the following: Parent > Child > Grandchild
      max_association_depth: 0
